"""In-memory outbox — local stand-in for the Scheduled Message Store.

Satisfies the ``OutboxStore`` Protocol. The deployed system persists
scheduled messages in SQLite/PostgreSQL (``scheduled_messages``,
``ROOT_IMPLEMENTATION.md`` §7.3) for the scheduler/dispatcher to pick up
inside each contact window; this implementation keeps them in a list so
the pipeline runs end-to-end locally.
"""

from __future__ import annotations

from credit_engine.worker.contracts import ScheduledMessage


class InMemoryOutbox:
    """Append-only in-memory store of scheduled messages."""

    def __init__(self) -> None:
        self._messages: list[ScheduledMessage] = []

    def save(self, message: ScheduledMessage) -> None:
        """Persist one scheduled message."""
        self._messages.append(message)

    def all_messages(self) -> list[ScheduledMessage]:
        """Return a copy of every stored message (insertion order)."""
        return list(self._messages)

    def for_person(self, person_id: str) -> list[ScheduledMessage]:
        """Return every stored message for one person ID."""
        return [m for m in self._messages if m.person_id == person_id]

    def for_batch(self, batch_id: str) -> list[ScheduledMessage]:
        """Return every stored message generated by one batch."""
        return [m for m in self._messages if m.batch_id == batch_id]
